### ISSUE TITLE
Dynamic creation of dataflow graphs

### ISSUE THREAD

**Issue by JosephWagner** [frankmcsherry/timely-dataflow#120]
I'm back with more questions! I'm going to state the problem/task I'm trying to solve first. I'm curious what's the correct/idiomatic approach.

Consider a stream of records identified by some composite primary key ((foo_id, bar_id, baz_id), value). Now lets say I want to compute aggregates by grouping by bar and baz and summing over foo. Now normally I could just use the aggregate operator, but the extra wrinkle is that foo_ids are related to each other via a hierarchy and I want to compute sums for every node in the tree.

So lets say the hierarchy is like {1: {2: [5,6], 3: [7,8,9]} and my input records are for ids 5,6,7,8,9 and I want to compute 1, 2 and 3.

I've done this using unary_frontier -- take each record, group it by bar/baz correctly, and accumulate it into its parent foo id. Once I get a notification that all foos within a bar/baz group have been input into the dataflow, I aggregate the rest of the way up the hierarchy and emit the aggregates. What I'm curious about is if putting all the logic into the custom operator is the "best" (most idiomatic? Best performance?) way to do this, vs creating more operators and putting more logic in timely control flow.

It's been working great on 1-2 million test records, but the full scale of my problem is ~1-5 billion records/~1-30 tb (each "value" in my case is large-ish array). I'm pretty sure this could be done differently if I was smarter about using timely control flow/ subscoping... I could see adding a nested scope for each level of this hierarchy and then using aggregate. Is that a good way to solve this problem?

What if the hierarchy isn't known at compile time? Can I create multiple subscopes if I don't know how many I'll need until runtime?

**Comment by frankmcsherry** [comment]
Hello!

What you are doing seems like a pretty reasonable start. It should balance the work pretty well as long as there is a decent distribution over the composite (bar,baz) keys (so that work gets balanced between the workers). The only reason I could think to do anything different is if this work is not balanced, that is when you look at the distribution of composite keys there are some that would swamp a worker.

There are some other approaches you could take that would be "more robust" in the presence of messed up distributions of keys, though they would have additional costs for that generality too. The one that comes to mind is to

1. Do a grouping and aggregation by (foo, bar, baz).
2. Repeatedly (using an iterative scope) map each foo to its parent in the hierarchy, and aggregate by (foo_parent, bar, baz).

This will distribute all the work by a richer (foo, bar, baz) key and might avoid skew in (bar, baz). It adds the complexity of the repeated shuffling as you go up the hierarchy, which costs in communication but could be worth it if you are balancing the work better. Also, as you go up the hierarchy the data collapse to fewer aggregates and the volume reduces, and so does the additional cost of shuffling.

If you are getting records with foo values both 5 and 2, so at varying levels of the hierarchy, you would want to use timestamps to finish a (foo, bar, baz) group at a "time" that depends on foo, so that each (foo, bar, baz) produces just one aggregate (rather than one for each level below it, as results trickle in).

It's an interesting computation, and probably pretty common, so I'd be happy to help either check some code, or prototype up what I'm talking about if it isn't super clear.

**Comment by JosephWagner** [comment]
Thanks for your explanation. I think I've whipped up a prototype that does what you suggest. I can see how this method avoids the problem of dynamic graph generation, because one just needs to set the loop variable to equal the number of levels in the hierarchy.

I think this doesn't solve the problem you mentioned of incoming leaf records that exist at multiple levels of the hierarchy. I'm a little hazy on what you mean by using timestamps -- if I understand correctly, every iteration inside the subscope will have a new timestamp, so I can use that to know what level of the hierarchy we're on. How can a "time" depend on foo?

`

  extern crate timely;

  use std::collections::HashMap;
  use std::iter::Iterator;

  use std::collections::hash_map::DefaultHasher;
  use std::hash::{Hash, Hasher};

  use timely::dataflow::{Scope, InputHandle, ProbeHandle};
  use timely::dataflow::operators::{Inspect, Probe, Enter, Leave, Map, Concat};
  use timely::dataflow::operators::feedback::{LoopVariable, ConnectLoop};
  use timely::dataflow::operators::aggregation::Aggregate;

  fn main() {
      // initializes and runs a timely dataflow.
      timely::execute_from_args(std::env::args(), |worker| {


          // create input and output handles.
          let mut input = InputHandle::new();
          let mut probe = ProbeHandle::new();

          // map of child to parent
          let hier: HashMap<isize, isize> = vec![1, 2, 3, 4, 5, 6, 7, 8].into_iter() // children
              .zip(vec![0, 1, 1, 2, 2, 3, 3, 3].into_iter()) //parents
              .collect();

          worker.dataflow(|scope| {

              let stream = input.to_stream(scope);

              let aggs = scope.scoped::<u64, _, _>( |subscope | {
                  let this_hier = hier.clone();
 
                  let (handle, cycle) = subscope.loop_variable(1, 1);

                  let inner_loop = stream.enter(subscope).concat(&cycle);
                  let aggs = inner_loop
                      .map(move |((foo, br, bz), val)| ((this_hier[&foo], br, bz), val))
                      .aggregate(
                          |_key, val, agg| { *agg += val; },
                          |key, agg: isize| (key, agg),
                          | &(f, br, bz) | {
                              let mut grouper = DefaultHasher::new();
                              let group = (f, br, bz);
                              group.hash(&mut grouper);
                              grouper.finish()
                          });
                  aggs.connect_loop(handle);
                  aggs.leave()
              });

          stream.concat(&aggs)
              .inspect(|x| println!("seen {:?}", x))
              .probe_with(&mut probe);
          });


          // records with only leaves of hierarchy
          let example_input = hier
              .keys()
              .collect::<Vec<_>>()
              .into_iter()
              .filter(|foo| ![1,2,3].contains(&foo))
              .map(|foo| ((*foo, 1, 1), 1))
              .collect::<Vec<_>>();
  
          let mut all_inputs = vec![];
          for new_bar in 0..2 {
              all_inputs
                  .extend(example_input
                        .clone()
                        .into_iter()
                        .map(|((foo, _bar, baz), val)| ((foo, new_bar, baz), val))
                          .collect::<Vec<_>>()
                        );
          }

          input.send_batch(&mut all_inputs);
          while probe.less_than(input.time()) {
              worker.step();
          }
          input.advance_to(1);

      }).unwrap();
  }

`

**Comment by frankmcsherry** [comment]
I'll ponder your code over coffee today, but let me try and explain what I meant about things coming in at different rounds.

Imagine you know that there are at most 1,000 levels to the hierarchy. Also imagine that you can tell by looking at `foo` that it is `foo.level()` levels from the top (say level `0` being the top). Then what you might want to do is hold off on doing the aggregation for `(foo, bar, baz)` until iteration `1000 - foo.level()`; this ensures that anything that might contribute to `foo` has arrived, and you won't need to issue further aggregates.

This wouldn't be a problem if all of your inputs started at level 1,000 because everyone would roll up in a coordinated fashion. But if folks do arrive at various levels then the aggregation operator would want to hold back their aggregation until other records had arrived.

**Comment by JosephWagner** [comment]
Thanks for the suggestion, Frank. I ended up using enter_at, as you suggested, for my 1 million record test. It ended up being easier to read than my original method of aggregating inside an operator.

The performance wasn't as good though -- but it was a good exercise in using subscopes. 


Here's what it ended up looking like, on the "foo" example from above. (I ended up creating a hierarchy object to get those helper methods parent_of and level_of):


```
          let hier = Hierarchy::new();

          worker.dataflow(|scope| {

              let stream = input.to_stream(scope);

              let aggs = scope.scoped::<u64, _, _>( |subscope | {
                  let num_levels = 10;
                  let (handle, cycle) = subscope.loop_variable(num_levels, 1);
                  let hier2 = hier.clone();

                  let inner_loop = stream
                      .enter_at(subscope,
                                move |&((foo, _br, _bz), _val)| num_levels - hier2.level_of(&foo) as u64)
                      .concat(&cycle);
                  let aggs = inner_loop
                      .map(move |((foo, br, bz), val)| ((hier.parent_of(&foo), br, bz), val))
                      .aggregate(
                          |_key, val, agg| { *agg += val; },
                          |key, agg: isize| (key, agg),
                          | &(f, br, bz) | {
                              let mut grouper = DefaultHasher::new();
                              let group = (f, br, bz);
                              group.hash(&mut grouper);
                              grouper.finish()
                          })
                  .filter(|&((foo, _br, _bz), _val)| foo != 0);
                  aggs.connect_loop(handle);
                  aggs.leave()
              });

          stream.concat(&aggs)
              .inspect(|x| println!("seen {:?}", x))
              .probe_with(&mut probe);
          });

```

**Comment by JosephWagner** [comment]
Thanks for the advice on how to do this uneven aggregation. I think this ticket can be closed.
