### ISSUE TITLE
Worker seized up when create connection with another one

### ISSUE THREAD

**Issue by zjureel** [frankmcsherry/timely-dataflow#148]
When I setup timely-dataflow to do some computations, some workers have seized up with following error informations:
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying
worker 141:	error connecting to worker 83: Connection refused (os error 111); retrying

Is there limit of retry for worker connections, and how can I config the limit of retry times? Thanks

**Comment by zjureel** [comment]
@frankmcsherry Could you please have a look when you're free, THX

**Comment by frankmcsherry** [comment]
Hi!

There is no retry limit, and to change the limit you would need to manually tweak the `timely_communication` crate. The error shows up when you have a worker that can't connect to an end-point that you've specified, either because i. there is no timely worker running there, ii. there is a typo in the address you've specified, or iii. there is a firewall that prevents connection. I'd check these things out, and in the meantime ^C the process that can't connect.

Cheers,
Frank

**Comment by frankmcsherry** [comment]
Thank you for the tip. Can you explain how to reproduce the problem?

**Comment by zjureel** [comment]
Sorry for reply later. I found another problem that my timely job always exit for out of memory even when I use 30G in each worker. Will it cause the OOM problem of timely operator when some operators after it  are too slow, such as output? If it would, is there any suggestions about how to control the flow and solve the OOM problem? Thanks
