### ISSUE TITLE
What's the meaning of returned bool of Operate::pull_internal_progress ? 

### ISSUE THREAD

**Issue by qiuxiafei** [frankmcsherry/timely-dataflow#166]
Hi, @frankmcsherry !

In the Operate trait's code, it is said that: 
> Returns a bool indicating if there is any unreported work remaining (e.g. work that doesn't project on an output).

But I'm not clear about the exact meaning of "unreported work remaining". For example, if a FlattenMap receives one single input and produces 10 output records, but only writes 6 of them to the 
 output, so are the other 4 records the so called unreported remained work?

But I found no operators returning `true` in timely's code. If someone wanna return a `true`, he has to build the operator from scratch instead of using unary, binary, builder_rs, biulder_raw or whatever.

So is it an intentional design to allow this kind of operation? If it is, what's the benifit and what's the use case?

Thanks!

**Comment by frankmcsherry** [comment]
If your `flat_map` operator retains a capability (which you would need to do if you wanted to send the remaining four records), you don't need to return true. The return of true is there because there are cases where operators have non-message and non-capability reasons to want to remain active.

The most common one is `Subgraph`, which is what gets created each time you create a timely dataflow scope. This is an operator, and it may need to keep executing due to strictly internal messages and capabilities, not ones that it has expressed upwards.

Other use cases include operators that have external side effects that need to complete, for example writing to a Kafka queue, and for which shutting down the operator would abort the writes rather than force them to complete (the current Kafka adaptor blocks in shutdown until all writes are complete, which is arguably a bad design).

**Comment by qiuxiafei** [comment]
Got it. Thanks!
