### ISSUE TITLE
Abomonate with Enum's

### ISSUE THREAD

**Issue by bfrog** [frankmcsherry/timely-dataflow#24]
I'm working on trying out timely with a more realistic use case I have and I'd like to use structs...

one of my structs looks like this...

``` rust
enum EventType {
    Hover = 1,
    Click = 2,
}

struct Event {
   event_type: EventType,
   // other simple fields
}

unsafe_abomonate!(Event : event_type, ....);
```
 
The macro of course does not like the EventType field since there's no Abomonation trait impl for it. Seems like I could implement it myself though thats highly discouraged. I could just switch to an integer type, but that means rust no longer gives me the nice error when I don't match all possibilities when doing stuff like...

``` rust
match event.event_type { .... }
```

I think in general abomonate is cool, just wondering what your thoughts are here

**Comment by frankmcsherry** [comment]
You are totally right. I should make a macro for `enum`s. Erm. I would like to do this, it shouldn't be hard, but I'm not sure I can safely bang it out in the next week or so. The pattern (which you can see from the `abomonate!` macro) is that each method of the trait should just call the corresponding method on each of the struct member fields, which is just going to be a big match for each method.

However, in your case you can just do 

`impl Abomonation for EventType {}`

because the default implementations of `Abomonation` methods are "don't worry about chasing any pointers", and you don't have any to chase. What it means is that your enum will basically be `memcpy`d around, which is probably what you want (but bear in mind that abomonation doesn't do input validation, or work with different endianness, architectures, etc).

**Comment by bfrog** [comment]
This seemed to work as expected! I have a new fun issue to work out, but its not related to this. Thanks!
