### ISSUE TITLE
Periodic State Saving

### ISSUE THREAD

**Issue by bfrog** [frankmcsherry/timely-dataflow#29]
So in my example I had a PR for I essentially had a bunch of aggregators, if I have a continuous calculation I'd like to persist my aggregator state every so often in real time (like every few minutes or something) how would you suggest going about doing that?

**Comment by frankmcsherry** [comment]
I think this is something that you could do pretty easily, but which wouldn't fit in to the recent aggregate methods. Two ways I can think of are:

1. Copy/paste the aggregation / state_machine code, and just have some logic that says "if time_since_checkpoint > 5, checkpoint" or such. You'll know exactly what it does, which is good.

2. Use the timestamps within timely to represent something like "seconds" or "checkpoint epochs", and tweak the aggregator to do a full dump each epoch, or every 5*60th epoch, etc. This lines up timely's main feature (consistency along timestamp lines) with what you want, and ensures that you get a semantically meaningful snapshot.

Depending on how you want to persist things, you could just hack the operator to write the data out for you. Alternately, it might make sense to pipe the data to a new operator which persists the data without blocking (e.g. sets up a bunch of non-blocking writes, with bounded amounts of data, etc). There is an operator sort-of like this called `capture`, which writes data out to a `W: Write` so that it can be replayed into timely. This may be helpful, or it may be a red herring. :)

**Comment by bfrog** [comment]
I think that makes sense, I'll have to play around more :+1:
