### ISSUE TITLE
Product<TOuter, TInner> implements total order

### ISSUE THREAD

**Issue by gandro** [frankmcsherry/timely-dataflow#42]
I'm not completely certain if this is a bug, but I found it very confusing that `Product<TOuter, TInner>` has an (automatically) derived implementation of the `Ord` trait which is incompatible with its (manually implemented) `PartialOrd` implementation. Example:

```
let a = Product::new(0, 1);
let b = Product::new(1, 0);
println!("{:?}", a.cmp(&b)); // A is less than B
println!("{:?}", a.partial_cmp(&b)); // A is incomparable to B
```

It seems to be the case that `Extract` is also requiring timestamps to implement `Ord`, so I'm not sure what this means.

**Comment by frankmcsherry** [comment]
Hi. This is intentional, if understandably confusing. To be clear, I don't believe the implementations are "incompatible", because when two elements are partially ordered they are also totally ordered.

The intent here, for what it is worth, is to allow the use of an arbitrary partial order (of course) but to allow the user to extend that partial order when it is important to do things like sort the data. 

In the case of `extract`, the `T: Ord` constraint exists so that the output results can be displayed in a canonical representation; otherwise when two incomparable timestamps are produced, the output could be non-deterministic. The main goal of `extract` was to allow one to extract the output of a computation for purposes of correctness testing. This could be done in a more complex way (e.g. define equality as set equality on pairs `(T, Vec<Data>)`) but this makes all the tests inscrutable.

Is it causing a problem other than being confusing? I'm up for thinking out other ways of doing this, but it has been helpful a few times (here, and also in differential dataflow where all data must implement `Ord`, again for canonicalization reasons).

**Comment by gandro** [comment]
Ah, I see. No, it is not causing any real problems. I just accidentally called `.cmp()` instead of `.partial_cmp()` when debugging and got really confused for a moment.

Thanks a lot for the fast reply!  :)
