### ISSUE TITLE
Comparison to Apache Spark (which I believe was inspired by Dryad)

### ISSUE THREAD

**Issue by nchammas** [frankmcsherry/timely-dataflow#55]
This may be premature, but I wondering if the authors could share a few thoughts for the data engineering laity on the conceptual (and perhaps also practical) difference between Timely Dataflow and Apache Spark.

I believe Apache Spark was inspired by the Dryad research project at Microsoft, which was a predecessor to the Naiad research project, which in turn inspired Timely Dataflow. (Did I get that right?)

**Comment by frankmcsherry** [comment]
Hello,

There's lots to say about the differences. :)  Probably the best place to start is the Naiad paper (http://sigops.org/sosp/sosp13/papers/p439-murray.pdf) which outlines the architecture and contrasts a bit with the standard batch processor design. The Rust implementation follows roughly the same architecture, with several tweaks to the progress tracking logic (and the lean Rust "no runtime").

I think the main difference is that Naiad and the Rust version maintain persistent tasks that continually send and receive data, rather than starting and stopping worker tasks as most batch processors do. This allows really fast turn-around on "scheduling", where you can get in and out of an operator in a few hundred nanoseconds, vs usually milliseconds at least for Spark et al. The down side of this is that since you haven't broken your computation into lots of independent tasks, if something goes wrong you have a more complicated story about how to fix it (e.g. "restart" in the Rust version).

For some more detail, this (now somewhat old) post (https://github.com/frankmcsherry/blog/blob/master/posts/2015-07-08.md) talks about the difference in the performance of GraphX and timely dataflow for graph processing (PageRank, specifically). There are a bunch of points made there about differences, mostly that there's not much runtime in your way with timely.

**Comment by frankmcsherry** [comment]
And, your lineage seems mostly right, except that I don't have specific knowledge about where Spark got their inspiration from. It has a lot in common with DryadLINQ and Nectar, but was a contemporary.

**Comment by nchammas** [comment]
Thanks for the info. This is good enough for me for starters. 👍

**Comment by frankmcsherry** [comment]
If you have other questions, totally drop in and ask. You can also tweet and email and whatever you like best. :)
